// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/lagzi/EntSymbolBug/ent/runtime.go

const (
	Version = "v0.10.2-0.20220620053230-311d76067960"           // Version of ent codegen.
	Sum     = "h1:LmGtK0ahsk+Uh1uArTPiZIra4odGGCZyGmicEIf2dkQ=" // Sum of ent codegen.
)
