// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/lagzi/EntSymbolBug/ent/runtime.go

const (
	Version = "v0.10.2-0.20220606082056-dd4519f935a6"           // Version of ent codegen.
	Sum     = "h1:bCKhU3VSCEInjxC1KmkRySaFwqCI4zYnX2F6oLISpLo=" // Sum of ent codegen.
)
