// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/lagzi/EntSymbolBug/ent/runtime.go

const (
	Version = "v0.10.2-0.20220629115610-f1662d9197e7"           // Version of ent codegen.
	Sum     = "h1:mkbGXK2WDdz3Yadt3yXbCJFCwzGI9kq+mr4lws1YZgo=" // Sum of ent codegen.
)
