-- create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "age" bigint NOT NULL, "name" character varying NOT NULL, PRIMARY KEY ("id"));
-- create "pictures" table
CREATE TABLE "pictures" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "url" character varying NOT NULL, PRIMARY KEY ("id"));
-- create "user_user_to_picture_edge_very_long_name_longer_than_the_amount_that_postgres_can_really_handle" table
CREATE TABLE "user_user_to_picture_edge_very_long_name_longer_than_the_amount_that_postgres_can_really_handle" ("user_id" bigint NOT NULL, "picture_id" bigint NOT NULL, PRIMARY KEY ("user_id", "picture_id"), CONSTRAINT "user_user_to_picture_edge_very_long_name_longer_than_the_amount_that_postgres_can_really_handle_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE, CONSTRAINT "user_user_to_picture_edge_very_long_name_longer_than_the_amount_that_postgres_can_really_handle_picture_id" FOREIGN KEY ("picture_id") REFERENCES "pictures" ("id") ON DELETE CASCADE);
