// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PicturesColumns holds the columns for the "pictures" table.
	PicturesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "url", Type: field.TypeString},
	}
	// PicturesTable holds the schema information for the "pictures" table.
	PicturesTable = &schema.Table{
		Name:       "pictures",
		Columns:    PicturesColumns,
		PrimaryKey: []*schema.Column{PicturesColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "age", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserUserToPictureEdgeVeryLongNameLongerThanTheAmountThatPostgresCanReallyHandleColumns holds the columns for the "user_user_to_picture_edge_very_long_name_longer_than_the_amount_that_postgres_can_really_handle" table.
	UserUserToPictureEdgeVeryLongNameLongerThanTheAmountThatPostgresCanReallyHandleColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "picture_id", Type: field.TypeInt},
	}
	// UserUserToPictureEdgeVeryLongNameLongerThanTheAmountThatPostgresCanReallyHandleTable holds the schema information for the "user_user_to_picture_edge_very_long_name_longer_than_the_amount_that_postgres_can_really_handle" table.
	UserUserToPictureEdgeVeryLongNameLongerThanTheAmountThatPostgresCanReallyHandleTable = &schema.Table{
		Name:       "user_user_to_picture_edge_very_long_name_longer_than_the_amount_that_postgres_can_really_handle",
		Columns:    UserUserToPictureEdgeVeryLongNameLongerThanTheAmountThatPostgresCanReallyHandleColumns,
		PrimaryKey: []*schema.Column{UserUserToPictureEdgeVeryLongNameLongerThanTheAmountThatPostgresCanReallyHandleColumns[0], UserUserToPictureEdgeVeryLongNameLongerThanTheAmountThatPostgresCanReallyHandleColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_user_to_picture_edge_very_long_name_longer_than_the_amount_that_postgres_can_really_handle_user_id",
				Columns:    []*schema.Column{UserUserToPictureEdgeVeryLongNameLongerThanTheAmountThatPostgresCanReallyHandleColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_user_to_picture_edge_very_long_name_longer_than_the_amount_that_postgres_can_really_handle_picture_id",
				Columns:    []*schema.Column{UserUserToPictureEdgeVeryLongNameLongerThanTheAmountThatPostgresCanReallyHandleColumns[1]},
				RefColumns: []*schema.Column{PicturesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PicturesTable,
		UsersTable,
		UserUserToPictureEdgeVeryLongNameLongerThanTheAmountThatPostgresCanReallyHandleTable,
	}
)

func init() {
	UserUserToPictureEdgeVeryLongNameLongerThanTheAmountThatPostgresCanReallyHandleTable.ForeignKeys[0].RefTable = UsersTable
	UserUserToPictureEdgeVeryLongNameLongerThanTheAmountThatPostgresCanReallyHandleTable.ForeignKeys[1].RefTable = PicturesTable
}
