// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// WorkerContainedInformationsColumns holds the columns for the "worker_contained_informations" table.
	WorkerContainedInformationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// WorkerContainedInformationsTable holds the schema information for the "worker_contained_informations" table.
	WorkerContainedInformationsTable = &schema.Table{
		Name:       "worker_contained_informations",
		Columns:    WorkerContainedInformationsColumns,
		PrimaryKey: []*schema.Column{WorkerContainedInformationsColumns[0]},
	}
	// WorkerNetworkSettingsColumns holds the columns for the "worker_network_settings" table.
	WorkerNetworkSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "worker_contained_information_network_settings", Type: field.TypeInt, Unique: true, Nullable: true},
	}
	// WorkerNetworkSettingsTable holds the schema information for the "worker_network_settings" table.
	WorkerNetworkSettingsTable = &schema.Table{
		Name:       "worker_network_settings",
		Columns:    WorkerNetworkSettingsColumns,
		PrimaryKey: []*schema.Column{WorkerNetworkSettingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "worker_network_settings_worker_contained_informations_network_settings",
				Columns:    []*schema.Column{WorkerNetworkSettingsColumns[1]},
				RefColumns: []*schema.Column{WorkerContainedInformationsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "workernetworksettings_worker_contained_information_network_settings",
				Unique:  false,
				Columns: []*schema.Column{WorkerNetworkSettingsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		WorkerContainedInformationsTable,
		WorkerNetworkSettingsTable,
	}
)

func init() {
	WorkerNetworkSettingsTable.ForeignKeys[0].RefTable = WorkerContainedInformationsTable
}
