// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lagzi/EntSymbolBug/ent/component"
	"github.com/lagzi/EntSymbolBug/ent/picture"
	"github.com/lagzi/EntSymbolBug/ent/predicate"
	"github.com/lagzi/EntSymbolBug/ent/user"
)

// PictureUpdate is the builder for updating Picture entities.
type PictureUpdate struct {
	config
	hooks    []Hook
	mutation *PictureMutation
}

// Where appends a list predicates to the PictureUpdate builder.
func (pu *PictureUpdate) Where(ps ...predicate.Picture) *PictureUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetUpdateTime sets the "update_time" field.
func (pu *PictureUpdate) SetUpdateTime(t time.Time) *PictureUpdate {
	pu.mutation.SetUpdateTime(t)
	return pu
}

// SetOtherImportantThing sets the "other_important_thing" field.
func (pu *PictureUpdate) SetOtherImportantThing(s string) *PictureUpdate {
	pu.mutation.SetOtherImportantThing(s)
	return pu
}

// SetTimestamp sets the "timestamp" field.
func (pu *PictureUpdate) SetTimestamp(t time.Time) *PictureUpdate {
	pu.mutation.SetTimestamp(t)
	return pu
}

// SetUserID sets the "user" edge to the User entity by ID.
func (pu *PictureUpdate) SetUserID(id int) *PictureUpdate {
	pu.mutation.SetUserID(id)
	return pu
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (pu *PictureUpdate) SetNillableUserID(id *int) *PictureUpdate {
	if id != nil {
		pu = pu.SetUserID(*id)
	}
	return pu
}

// SetUser sets the "user" edge to the User entity.
func (pu *PictureUpdate) SetUser(u *User) *PictureUpdate {
	return pu.SetUserID(u.ID)
}

// SetComponentID sets the "component" edge to the Component entity by ID.
func (pu *PictureUpdate) SetComponentID(id int) *PictureUpdate {
	pu.mutation.SetComponentID(id)
	return pu
}

// SetNillableComponentID sets the "component" edge to the Component entity by ID if the given value is not nil.
func (pu *PictureUpdate) SetNillableComponentID(id *int) *PictureUpdate {
	if id != nil {
		pu = pu.SetComponentID(*id)
	}
	return pu
}

// SetComponent sets the "component" edge to the Component entity.
func (pu *PictureUpdate) SetComponent(c *Component) *PictureUpdate {
	return pu.SetComponentID(c.ID)
}

// Mutation returns the PictureMutation object of the builder.
func (pu *PictureUpdate) Mutation() *PictureMutation {
	return pu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (pu *PictureUpdate) ClearUser() *PictureUpdate {
	pu.mutation.ClearUser()
	return pu
}

// ClearComponent clears the "component" edge to the Component entity.
func (pu *PictureUpdate) ClearComponent() *PictureUpdate {
	pu.mutation.ClearComponent()
	return pu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PictureUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	pu.defaults()
	if len(pu.hooks) == 0 {
		affected, err = pu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PictureMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pu.mutation = mutation
			affected, err = pu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pu.hooks) - 1; i >= 0; i-- {
			if pu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PictureUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PictureUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PictureUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pu *PictureUpdate) defaults() {
	if _, ok := pu.mutation.UpdateTime(); !ok {
		v := picture.UpdateDefaultUpdateTime()
		pu.mutation.SetUpdateTime(v)
	}
}

func (pu *PictureUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   picture.Table,
			Columns: picture.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: picture.FieldID,
			},
		},
	}
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: picture.FieldUpdateTime,
		})
	}
	if value, ok := pu.mutation.OtherImportantThing(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: picture.FieldOtherImportantThing,
		})
	}
	if value, ok := pu.mutation.Timestamp(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: picture.FieldTimestamp,
		})
	}
	if pu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   picture.UserTable,
			Columns: []string{picture.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   picture.UserTable,
			Columns: []string{picture.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.ComponentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   picture.ComponentTable,
			Columns: []string{picture.ComponentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: component.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.ComponentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   picture.ComponentTable,
			Columns: []string{picture.ComponentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: component.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{picture.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// PictureUpdateOne is the builder for updating a single Picture entity.
type PictureUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PictureMutation
}

// SetUpdateTime sets the "update_time" field.
func (puo *PictureUpdateOne) SetUpdateTime(t time.Time) *PictureUpdateOne {
	puo.mutation.SetUpdateTime(t)
	return puo
}

// SetOtherImportantThing sets the "other_important_thing" field.
func (puo *PictureUpdateOne) SetOtherImportantThing(s string) *PictureUpdateOne {
	puo.mutation.SetOtherImportantThing(s)
	return puo
}

// SetTimestamp sets the "timestamp" field.
func (puo *PictureUpdateOne) SetTimestamp(t time.Time) *PictureUpdateOne {
	puo.mutation.SetTimestamp(t)
	return puo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (puo *PictureUpdateOne) SetUserID(id int) *PictureUpdateOne {
	puo.mutation.SetUserID(id)
	return puo
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (puo *PictureUpdateOne) SetNillableUserID(id *int) *PictureUpdateOne {
	if id != nil {
		puo = puo.SetUserID(*id)
	}
	return puo
}

// SetUser sets the "user" edge to the User entity.
func (puo *PictureUpdateOne) SetUser(u *User) *PictureUpdateOne {
	return puo.SetUserID(u.ID)
}

// SetComponentID sets the "component" edge to the Component entity by ID.
func (puo *PictureUpdateOne) SetComponentID(id int) *PictureUpdateOne {
	puo.mutation.SetComponentID(id)
	return puo
}

// SetNillableComponentID sets the "component" edge to the Component entity by ID if the given value is not nil.
func (puo *PictureUpdateOne) SetNillableComponentID(id *int) *PictureUpdateOne {
	if id != nil {
		puo = puo.SetComponentID(*id)
	}
	return puo
}

// SetComponent sets the "component" edge to the Component entity.
func (puo *PictureUpdateOne) SetComponent(c *Component) *PictureUpdateOne {
	return puo.SetComponentID(c.ID)
}

// Mutation returns the PictureMutation object of the builder.
func (puo *PictureUpdateOne) Mutation() *PictureMutation {
	return puo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (puo *PictureUpdateOne) ClearUser() *PictureUpdateOne {
	puo.mutation.ClearUser()
	return puo
}

// ClearComponent clears the "component" edge to the Component entity.
func (puo *PictureUpdateOne) ClearComponent() *PictureUpdateOne {
	puo.mutation.ClearComponent()
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PictureUpdateOne) Select(field string, fields ...string) *PictureUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Picture entity.
func (puo *PictureUpdateOne) Save(ctx context.Context) (*Picture, error) {
	var (
		err  error
		node *Picture
	)
	puo.defaults()
	if len(puo.hooks) == 0 {
		node, err = puo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PictureMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			puo.mutation = mutation
			node, err = puo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(puo.hooks) - 1; i >= 0; i-- {
			if puo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = puo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, puo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Picture)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from PictureMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PictureUpdateOne) SaveX(ctx context.Context) *Picture {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PictureUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PictureUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (puo *PictureUpdateOne) defaults() {
	if _, ok := puo.mutation.UpdateTime(); !ok {
		v := picture.UpdateDefaultUpdateTime()
		puo.mutation.SetUpdateTime(v)
	}
}

func (puo *PictureUpdateOne) sqlSave(ctx context.Context) (_node *Picture, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   picture.Table,
			Columns: picture.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: picture.FieldID,
			},
		},
	}
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Picture.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, picture.FieldID)
		for _, f := range fields {
			if !picture.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != picture.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: picture.FieldUpdateTime,
		})
	}
	if value, ok := puo.mutation.OtherImportantThing(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: picture.FieldOtherImportantThing,
		})
	}
	if value, ok := puo.mutation.Timestamp(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: picture.FieldTimestamp,
		})
	}
	if puo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   picture.UserTable,
			Columns: []string{picture.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   picture.UserTable,
			Columns: []string{picture.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.ComponentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   picture.ComponentTable,
			Columns: []string{picture.ComponentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: component.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.ComponentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   picture.ComponentTable,
			Columns: []string{picture.ComponentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: component.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Picture{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{picture.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
