// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/lagzi/EntSymbolBug/ent/component"
	"github.com/lagzi/EntSymbolBug/ent/picture"
	"github.com/lagzi/EntSymbolBug/ent/schema"
	"github.com/lagzi/EntSymbolBug/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	componentMixin := schema.Component{}.Mixin()
	componentMixinFields0 := componentMixin[0].Fields()
	_ = componentMixinFields0
	componentFields := schema.Component{}.Fields()
	_ = componentFields
	// componentDescCreateTime is the schema descriptor for create_time field.
	componentDescCreateTime := componentMixinFields0[0].Descriptor()
	// component.DefaultCreateTime holds the default value on creation for the create_time field.
	component.DefaultCreateTime = componentDescCreateTime.Default.(func() time.Time)
	// componentDescUpdateTime is the schema descriptor for update_time field.
	componentDescUpdateTime := componentMixinFields0[1].Descriptor()
	// component.DefaultUpdateTime holds the default value on creation for the update_time field.
	component.DefaultUpdateTime = componentDescUpdateTime.Default.(func() time.Time)
	// component.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	component.UpdateDefaultUpdateTime = componentDescUpdateTime.UpdateDefault.(func() time.Time)
	pictureMixin := schema.Picture{}.Mixin()
	pictureMixinFields0 := pictureMixin[0].Fields()
	_ = pictureMixinFields0
	pictureFields := schema.Picture{}.Fields()
	_ = pictureFields
	// pictureDescCreateTime is the schema descriptor for create_time field.
	pictureDescCreateTime := pictureMixinFields0[0].Descriptor()
	// picture.DefaultCreateTime holds the default value on creation for the create_time field.
	picture.DefaultCreateTime = pictureDescCreateTime.Default.(func() time.Time)
	// pictureDescUpdateTime is the schema descriptor for update_time field.
	pictureDescUpdateTime := pictureMixinFields0[1].Descriptor()
	// picture.DefaultUpdateTime holds the default value on creation for the update_time field.
	picture.DefaultUpdateTime = pictureDescUpdateTime.Default.(func() time.Time)
	// picture.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	picture.UpdateDefaultUpdateTime = pictureDescUpdateTime.UpdateDefault.(func() time.Time)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreateTime is the schema descriptor for create_time field.
	userDescCreateTime := userMixinFields0[0].Descriptor()
	// user.DefaultCreateTime holds the default value on creation for the create_time field.
	user.DefaultCreateTime = userDescCreateTime.Default.(func() time.Time)
	// userDescUpdateTime is the schema descriptor for update_time field.
	userDescUpdateTime := userMixinFields0[1].Descriptor()
	// user.DefaultUpdateTime holds the default value on creation for the update_time field.
	user.DefaultUpdateTime = userDescUpdateTime.Default.(func() time.Time)
	// user.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	user.UpdateDefaultUpdateTime = userDescUpdateTime.UpdateDefault.(func() time.Time)
}
