// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lagzi/EntSymbolBug/ent/predicate"
	"github.com/lagzi/EntSymbolBug/ent/workernetworksettings"
)

// WorkerNetworkSettingsDelete is the builder for deleting a WorkerNetworkSettings entity.
type WorkerNetworkSettingsDelete struct {
	config
	hooks    []Hook
	mutation *WorkerNetworkSettingsMutation
}

// Where appends a list predicates to the WorkerNetworkSettingsDelete builder.
func (wnsd *WorkerNetworkSettingsDelete) Where(ps ...predicate.WorkerNetworkSettings) *WorkerNetworkSettingsDelete {
	wnsd.mutation.Where(ps...)
	return wnsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (wnsd *WorkerNetworkSettingsDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(wnsd.hooks) == 0 {
		affected, err = wnsd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*WorkerNetworkSettingsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			wnsd.mutation = mutation
			affected, err = wnsd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(wnsd.hooks) - 1; i >= 0; i-- {
			if wnsd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = wnsd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, wnsd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (wnsd *WorkerNetworkSettingsDelete) ExecX(ctx context.Context) int {
	n, err := wnsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (wnsd *WorkerNetworkSettingsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: workernetworksettings.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: workernetworksettings.FieldID,
			},
		},
	}
	if ps := wnsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, wnsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// WorkerNetworkSettingsDeleteOne is the builder for deleting a single WorkerNetworkSettings entity.
type WorkerNetworkSettingsDeleteOne struct {
	wnsd *WorkerNetworkSettingsDelete
}

// Exec executes the deletion query.
func (wnsdo *WorkerNetworkSettingsDeleteOne) Exec(ctx context.Context) error {
	n, err := wnsdo.wnsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{workernetworksettings.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (wnsdo *WorkerNetworkSettingsDeleteOne) ExecX(ctx context.Context) {
	wnsdo.wnsd.ExecX(ctx)
}
