// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lagzi/EntSymbolBug/ent/workercontainedinformation"
	"github.com/lagzi/EntSymbolBug/ent/workernetworksettings"
)

// WorkerNetworkSettingsCreate is the builder for creating a WorkerNetworkSettings entity.
type WorkerNetworkSettingsCreate struct {
	config
	mutation *WorkerNetworkSettingsMutation
	hooks    []Hook
}

// SetWorkerContainedInformationID sets the "worker_contained_information" edge to the WorkerContainedInformation entity by ID.
func (wnsc *WorkerNetworkSettingsCreate) SetWorkerContainedInformationID(id int) *WorkerNetworkSettingsCreate {
	wnsc.mutation.SetWorkerContainedInformationID(id)
	return wnsc
}

// SetNillableWorkerContainedInformationID sets the "worker_contained_information" edge to the WorkerContainedInformation entity by ID if the given value is not nil.
func (wnsc *WorkerNetworkSettingsCreate) SetNillableWorkerContainedInformationID(id *int) *WorkerNetworkSettingsCreate {
	if id != nil {
		wnsc = wnsc.SetWorkerContainedInformationID(*id)
	}
	return wnsc
}

// SetWorkerContainedInformation sets the "worker_contained_information" edge to the WorkerContainedInformation entity.
func (wnsc *WorkerNetworkSettingsCreate) SetWorkerContainedInformation(w *WorkerContainedInformation) *WorkerNetworkSettingsCreate {
	return wnsc.SetWorkerContainedInformationID(w.ID)
}

// Mutation returns the WorkerNetworkSettingsMutation object of the builder.
func (wnsc *WorkerNetworkSettingsCreate) Mutation() *WorkerNetworkSettingsMutation {
	return wnsc.mutation
}

// Save creates the WorkerNetworkSettings in the database.
func (wnsc *WorkerNetworkSettingsCreate) Save(ctx context.Context) (*WorkerNetworkSettings, error) {
	var (
		err  error
		node *WorkerNetworkSettings
	)
	if len(wnsc.hooks) == 0 {
		if err = wnsc.check(); err != nil {
			return nil, err
		}
		node, err = wnsc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*WorkerNetworkSettingsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = wnsc.check(); err != nil {
				return nil, err
			}
			wnsc.mutation = mutation
			if node, err = wnsc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(wnsc.hooks) - 1; i >= 0; i-- {
			if wnsc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = wnsc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, wnsc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*WorkerNetworkSettings)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from WorkerNetworkSettingsMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (wnsc *WorkerNetworkSettingsCreate) SaveX(ctx context.Context) *WorkerNetworkSettings {
	v, err := wnsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wnsc *WorkerNetworkSettingsCreate) Exec(ctx context.Context) error {
	_, err := wnsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wnsc *WorkerNetworkSettingsCreate) ExecX(ctx context.Context) {
	if err := wnsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wnsc *WorkerNetworkSettingsCreate) check() error {
	return nil
}

func (wnsc *WorkerNetworkSettingsCreate) sqlSave(ctx context.Context) (*WorkerNetworkSettings, error) {
	_node, _spec := wnsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, wnsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (wnsc *WorkerNetworkSettingsCreate) createSpec() (*WorkerNetworkSettings, *sqlgraph.CreateSpec) {
	var (
		_node = &WorkerNetworkSettings{config: wnsc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: workernetworksettings.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: workernetworksettings.FieldID,
			},
		}
	)
	if nodes := wnsc.mutation.WorkerContainedInformationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   workernetworksettings.WorkerContainedInformationTable,
			Columns: []string{workernetworksettings.WorkerContainedInformationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: workercontainedinformation.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.worker_contained_information_network_settings = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WorkerNetworkSettingsCreateBulk is the builder for creating many WorkerNetworkSettings entities in bulk.
type WorkerNetworkSettingsCreateBulk struct {
	config
	builders []*WorkerNetworkSettingsCreate
}

// Save creates the WorkerNetworkSettings entities in the database.
func (wnscb *WorkerNetworkSettingsCreateBulk) Save(ctx context.Context) ([]*WorkerNetworkSettings, error) {
	specs := make([]*sqlgraph.CreateSpec, len(wnscb.builders))
	nodes := make([]*WorkerNetworkSettings, len(wnscb.builders))
	mutators := make([]Mutator, len(wnscb.builders))
	for i := range wnscb.builders {
		func(i int, root context.Context) {
			builder := wnscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkerNetworkSettingsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, wnscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, wnscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, wnscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (wnscb *WorkerNetworkSettingsCreateBulk) SaveX(ctx context.Context) []*WorkerNetworkSettings {
	v, err := wnscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wnscb *WorkerNetworkSettingsCreateBulk) Exec(ctx context.Context) error {
	_, err := wnscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wnscb *WorkerNetworkSettingsCreateBulk) ExecX(ctx context.Context) {
	if err := wnscb.Exec(ctx); err != nil {
		panic(err)
	}
}
