// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lagzi/EntSymbolBug/ent/predicate"
	"github.com/lagzi/EntSymbolBug/ent/workercontainedinformation"
)

// WorkerContainedInformationDelete is the builder for deleting a WorkerContainedInformation entity.
type WorkerContainedInformationDelete struct {
	config
	hooks    []Hook
	mutation *WorkerContainedInformationMutation
}

// Where appends a list predicates to the WorkerContainedInformationDelete builder.
func (wcid *WorkerContainedInformationDelete) Where(ps ...predicate.WorkerContainedInformation) *WorkerContainedInformationDelete {
	wcid.mutation.Where(ps...)
	return wcid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (wcid *WorkerContainedInformationDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(wcid.hooks) == 0 {
		affected, err = wcid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*WorkerContainedInformationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			wcid.mutation = mutation
			affected, err = wcid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(wcid.hooks) - 1; i >= 0; i-- {
			if wcid.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = wcid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, wcid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (wcid *WorkerContainedInformationDelete) ExecX(ctx context.Context) int {
	n, err := wcid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (wcid *WorkerContainedInformationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: workercontainedinformation.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: workercontainedinformation.FieldID,
			},
		},
	}
	if ps := wcid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, wcid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// WorkerContainedInformationDeleteOne is the builder for deleting a single WorkerContainedInformation entity.
type WorkerContainedInformationDeleteOne struct {
	wcid *WorkerContainedInformationDelete
}

// Exec executes the deletion query.
func (wcido *WorkerContainedInformationDeleteOne) Exec(ctx context.Context) error {
	n, err := wcido.wcid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{workercontainedinformation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (wcido *WorkerContainedInformationDeleteOne) ExecX(ctx context.Context) {
	wcido.wcid.ExecX(ctx)
}
