// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lagzi/EntSymbolBug/ent/workercontainedinformation"
	"github.com/lagzi/EntSymbolBug/ent/workernetworksettings"
)

// WorkerContainedInformationCreate is the builder for creating a WorkerContainedInformation entity.
type WorkerContainedInformationCreate struct {
	config
	mutation *WorkerContainedInformationMutation
	hooks    []Hook
}

// SetNetworkSettingsID sets the "network_settings" edge to the WorkerNetworkSettings entity by ID.
func (wcic *WorkerContainedInformationCreate) SetNetworkSettingsID(id int) *WorkerContainedInformationCreate {
	wcic.mutation.SetNetworkSettingsID(id)
	return wcic
}

// SetNillableNetworkSettingsID sets the "network_settings" edge to the WorkerNetworkSettings entity by ID if the given value is not nil.
func (wcic *WorkerContainedInformationCreate) SetNillableNetworkSettingsID(id *int) *WorkerContainedInformationCreate {
	if id != nil {
		wcic = wcic.SetNetworkSettingsID(*id)
	}
	return wcic
}

// SetNetworkSettings sets the "network_settings" edge to the WorkerNetworkSettings entity.
func (wcic *WorkerContainedInformationCreate) SetNetworkSettings(w *WorkerNetworkSettings) *WorkerContainedInformationCreate {
	return wcic.SetNetworkSettingsID(w.ID)
}

// Mutation returns the WorkerContainedInformationMutation object of the builder.
func (wcic *WorkerContainedInformationCreate) Mutation() *WorkerContainedInformationMutation {
	return wcic.mutation
}

// Save creates the WorkerContainedInformation in the database.
func (wcic *WorkerContainedInformationCreate) Save(ctx context.Context) (*WorkerContainedInformation, error) {
	var (
		err  error
		node *WorkerContainedInformation
	)
	if len(wcic.hooks) == 0 {
		if err = wcic.check(); err != nil {
			return nil, err
		}
		node, err = wcic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*WorkerContainedInformationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = wcic.check(); err != nil {
				return nil, err
			}
			wcic.mutation = mutation
			if node, err = wcic.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(wcic.hooks) - 1; i >= 0; i-- {
			if wcic.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = wcic.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, wcic.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*WorkerContainedInformation)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from WorkerContainedInformationMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (wcic *WorkerContainedInformationCreate) SaveX(ctx context.Context) *WorkerContainedInformation {
	v, err := wcic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wcic *WorkerContainedInformationCreate) Exec(ctx context.Context) error {
	_, err := wcic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wcic *WorkerContainedInformationCreate) ExecX(ctx context.Context) {
	if err := wcic.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wcic *WorkerContainedInformationCreate) check() error {
	return nil
}

func (wcic *WorkerContainedInformationCreate) sqlSave(ctx context.Context) (*WorkerContainedInformation, error) {
	_node, _spec := wcic.createSpec()
	if err := sqlgraph.CreateNode(ctx, wcic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (wcic *WorkerContainedInformationCreate) createSpec() (*WorkerContainedInformation, *sqlgraph.CreateSpec) {
	var (
		_node = &WorkerContainedInformation{config: wcic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: workercontainedinformation.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: workercontainedinformation.FieldID,
			},
		}
	)
	if nodes := wcic.mutation.NetworkSettingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   workercontainedinformation.NetworkSettingsTable,
			Columns: []string{workercontainedinformation.NetworkSettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: workernetworksettings.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WorkerContainedInformationCreateBulk is the builder for creating many WorkerContainedInformation entities in bulk.
type WorkerContainedInformationCreateBulk struct {
	config
	builders []*WorkerContainedInformationCreate
}

// Save creates the WorkerContainedInformation entities in the database.
func (wcicb *WorkerContainedInformationCreateBulk) Save(ctx context.Context) ([]*WorkerContainedInformation, error) {
	specs := make([]*sqlgraph.CreateSpec, len(wcicb.builders))
	nodes := make([]*WorkerContainedInformation, len(wcicb.builders))
	mutators := make([]Mutator, len(wcicb.builders))
	for i := range wcicb.builders {
		func(i int, root context.Context) {
			builder := wcicb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkerContainedInformationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, wcicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, wcicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, wcicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (wcicb *WorkerContainedInformationCreateBulk) SaveX(ctx context.Context) []*WorkerContainedInformation {
	v, err := wcicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wcicb *WorkerContainedInformationCreateBulk) Exec(ctx context.Context) error {
	_, err := wcicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wcicb *WorkerContainedInformationCreateBulk) ExecX(ctx context.Context) {
	if err := wcicb.Exec(ctx); err != nil {
		panic(err)
	}
}
