// Code generated by entc, DO NOT EDIT.

package picture

const (
	// Label holds the string label denoting the picture type in the database.
	Label = "picture"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// EdgePicture holds the string denoting the picture edge name in mutations.
	EdgePicture = "picture"
	// Table holds the table name of the picture in the database.
	Table = "pictures"
	// PictureTable is the table that holds the picture relation/edge. The primary key declared below.
	PictureTable = "user_user_to_picture_edge_very_long_name_longer_than_the_amount_that_postgres_can_really_handle"
	// PictureInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	PictureInverseTable = "users"
)

// Columns holds all SQL columns for picture fields.
var Columns = []string{
	FieldID,
	FieldURL,
}

var (
	// PicturePrimaryKey and PictureColumn2 are the table columns denoting the
	// primary key for the picture relation (M2M).
	PicturePrimaryKey = []string{"user_id", "picture_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
