// Code generated by ent, DO NOT EDIT.

package workercontainedinformation

const (
	// Label holds the string label denoting the workercontainedinformation type in the database.
	Label = "worker_contained_information"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// EdgeNetworkSettings holds the string denoting the network_settings edge name in mutations.
	EdgeNetworkSettings = "network_settings"
	// Table holds the table name of the workercontainedinformation in the database.
	Table = "worker_contained_informations"
	// NetworkSettingsTable is the table that holds the network_settings relation/edge.
	NetworkSettingsTable = "worker_network_settings"
	// NetworkSettingsInverseTable is the table name for the WorkerNetworkSettings entity.
	// It exists in this package in order to avoid circular dependency with the "workernetworksettings" package.
	NetworkSettingsInverseTable = "worker_network_settings"
	// NetworkSettingsColumn is the table column denoting the network_settings relation/edge.
	NetworkSettingsColumn = "worker_contained_information_network_settings"
)

// Columns holds all SQL columns for workercontainedinformation fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
