// Code generated by ent, DO NOT EDIT.

package component

import (
	"time"
)

const (
	// Label holds the string label denoting the component type in the database.
	Label = "component"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldSomeID holds the string denoting the some_id field in the database.
	FieldSomeID = "some_id"
	// EdgePictures holds the string denoting the pictures edge name in mutations.
	EdgePictures = "pictures"
	// Table holds the table name of the component in the database.
	Table = "components"
	// PicturesTable is the table that holds the pictures relation/edge.
	PicturesTable = "pictures"
	// PicturesInverseTable is the table name for the Picture entity.
	// It exists in this package in order to avoid circular dependency with the "picture" package.
	PicturesInverseTable = "pictures"
	// PicturesColumn is the table column denoting the pictures relation/edge.
	PicturesColumn = "component_pictures"
)

// Columns holds all SQL columns for component fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldSomeID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
)
