// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Picture is the predicate function for picture builders.
type Picture func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
