// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// WorkerContainedInformation is the predicate function for workercontainedinformation builders.
type WorkerContainedInformation func(*sql.Selector)

// WorkerNetworkSettings is the predicate function for workernetworksettings builders.
type WorkerNetworkSettings func(*sql.Selector)
