// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Component is the predicate function for component builders.
type Component func(*sql.Selector)

// Picture is the predicate function for picture builders.
type Picture func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
